config/routes.rb
Rails.application.routes.draw do

  resources :productos
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def new
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  def show
    @producto = Producto.find(params[:id])
  end

  def new
  end

  def index
    @productos = Producto.all
  end

  def edit
    @producto = Producto.find(params[:id])
  end

  def update
    @producto = Producto.find(params[:id])
    if @producto.update_attributes(producto_params)
      # Handle a successful update.
    else
      render 'edit'
    end
  end

  private

    def producto_params
      params.require(:producto).permit(:title, :cantidad, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1>Bienvenido a Shopper</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum modi cum fugit quisquam sapiente quos odit, excepturi enim quam, deleniti reprehenderit illum, aut cupiditate eligendi inventore deserunt necessitatibus sit. Quam.</p>
  <a href="/productos">Ver todos los productos</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/productos/edit.html.erb
<div class="container">
  <h1>Editar</h1>
  <%= form_for(@producto) do |f| %>
    <%= render 'shared/error_messages', object: @producto %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :cantidad %>
    <%= f.text_field :cantidad, class: 'form-control' %>

    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>

    <%= f.submit "Guardar", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/productos/index.html.erb
<div class="container">
  <h1>Productos</h1>
  <div class="row">
    <% @productos.each do |producto| %>
      <div class="col s12 m4">
        <div class="producto card">
          <div class="producto-body card-content">
            <span class="card-title"><%= producto.title %></span>
            <p class="content description"><%=h truncate(producto.content, :length => 80) %></p>
            <span class="time">Cantidad: <%= producto.cantidad %></span>
            <p class="time">Fecha: <%= producto.created_at %></p>
          </div>
          <div class="card-action">
            <%= link_to 'Ver producto', producto_path(producto) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/productos/new.html.erb
<h1>Hola New producto</h1>

app/views/productos/show.html.erb
<div class="container">
  <h1><%= @producto.title %></h1>
  <p class="flow-text">
    <strong>Descripción:</strong>
    <%= @producto.content %>
  </p>
  <%= link_to 'Agregar al carrito', "", class: "btn btn-primary" %>
  <%= link_to 'Editar', edit_producto_path(@producto), class: "btn btn-primary" %>
</div>

app/views/shared/_error_messages.html.erb
<% if @producto.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@producto.errors.count, "error") %>.
    </div>
    <ul>
    <% @producto.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>